name: Release Package
on: [push]
#  release:
#    types:
#      - created
jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Maven
        uses: docker://maven:3.6.3-jdk-11-openj9
      - name: Package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn deploy -Dregistry=https://maven.pkg.github.com/gjobin/releases -Dtoken=$GITHUB_TOKEN