name: Release Package
on: [push]
#  release:
#    types:
#      - created
jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.3
      - name: Package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn deploy -Dregistry=https://maven.pkg.github.com/gjobin/releases -Dtoken=$GITHUB_TOKEN